# Type stub for python-ulid
# This fixes Pylance "could not be resolved" warning

from typing import Optional
from datetime import datetime

class ULID:
    """ULID (Universally Unique Lexicographically Sortable Identifier)"""
    
    def __init__(self, timestamp: Optional[datetime] = None) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @property
    def timestamp(self) -> datetime: ...
    @property
    def randomness(self) -> bytes: ...
