name: Backend CD

# Triggers ( configurar entorno a qa y dev tambien )
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest # VM

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Connect and Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          # una vez tengamos configurados los secrets
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # necesitamos generar esta
          port: 22
          script: |
            cd /back-dp2

            git pull origin main

            echo "Executing docker compose up..."
            docker compose up -d --build

            echo "Deleting unused Docker image files..."
            docker image prune -f
